### PR TITLE
Use HackMD markdown parser and add example files

### PR DESCRIPTION
**Pull request by nizaroni**
This uses a markdown parsing function I extracted from HackMD (now CodiMD). It supports some extra features that we use:

- GitHub style emoji like `:pizza:`
- Bootstrap style alert boxes like `:::danger`
- Embedded `<iframe>` tags for things like CodePen

I've also added some example course files to test the features.

### CODE REVIEW

**Comment by nizaroni** [comment]
I've also added support for YouTube codes like this `{%youtube kJQP7kiw5Fk %}`!

I realized that I was working on top of version 0.2.0 instead of 0.3.0. As soon as the repo is updated to version 0.3.0, I'll rebase, force push, and reopen the pull request.

**Comment by nizaroni** [comment]
Opening pull request in preparation to force-push.

**Comment by nizaroni** [comment]
Ready to merge!

**Review by guilleironhack — APPROVED** [review]
Looks good to me! Thank you very much 😄

**Pull request merged**
